# Use the official Python image as the base image
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements.txt file to the working directory
COPY requirements.txt .

# Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code to the working directory
COPY . .

# Copy the index.html file from the template folder to the working directory
COPY templates/index.html .

# Expose the port that the Flask application will be running on
EXPOSE 3000

# Start the Flask application
CMD ["python", "app.py"]
